# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspot', '0002_space_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='booked_for',
            field=models.IntegerField(default=1),
        ),
    ]
