# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspot', '0003_space_booked_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='booked_for',
            field=models.IntegerField(default=0),
        ),
    ]
