# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findspot', '0004_auto_20170407_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
